name: doxygen-deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy-vr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install doxygen
      run: sudo apt-get install -y doxygen

    #Run Doxygen on vr folder
    - name: Run Doxygen
      working-directory: ${{github.workspace}}/VRproject
      run: doxygen
    
    #Deploy html output from Doxygen to gh-pages branch
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        # The branch the action should deploy to.
        branch: gh-pages
        # The folder the action should deploy.
        folder: ${{github.workspace}}/VRproject/html
