name: doxygen-deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy-vr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install doxygen
      run: sudo apt-get install -y doxygen

    # Run Doxygen on vr folder
    - name: Run Doxygen
      working-directory: ${{ github.workspace }}/VRproject
      run: doxygen

    # Deploy html output from Doxygen to gh-pages branch
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: ${{ github.workspace }}/VRproject/html
        token: ${{ secrets.GITHUB_TOKEN }}  # <- FIXED HERE
